apiVersion: apps/v1 
kind: Deployment
metadata:
  name: web3app
  labels: 
     app: web3app

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: web3app

  template:
    metadata:
      labels:
        app: web3app
    spec:
      containers:
      - name: web3app
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1